{
    "functionName": "raise_unhandled_exception_not_in_except_clause",
    "className": null,
    "fileName": "/fabioz_&_PyDev.Debugger/tests_python_&_test_tracing_on_top_level.py",
    "projectName": "repos",
    "Label": false,
    "isTest": false,
    "Body": "try:\n    raise AssertionError()\nexcept RuntimeError:\n    pass\nmark_unhandled"
}