{
    "functionName": "test_exception_handling_with_response",
    "className": null,
    "fileName": "/RobertoPrevato_&_BlackSheep/itests_&_test_server.py",
    "projectName": "repos",
    "Label": false,
    "isTest": true,
    "Body": "response = session_two.get('/handled-crash')\nassert response.status_code == 200\nassert response.text == 'Fake exception, to test handlers'\n"
}