{
    "functionName": "test_default_error_msg",
    "className": "PyU4VUtilsTest",
    "fileName": "/MichaelMcAleer_&_PyU4V/PyU4V_&_tests_&_unit_tests_&_test_pyu4v_utils.py",
    "projectName": "repos",
    "Label": false,
    "isTest": true,
    "Body": "class FakePyU4VException(exception.PyU4VException):\n    message = 'default message'\nexc = FakePyU4VException()\nself.assertEqual('default message', six.text_type(exc))\n"
}