{
    "functionName": "test_no_data_error",
    "className": "PlotTest",
    "fileName": "/openworm_&_PyOpenWorm/tests_&_PlotTest.py",
    "projectName": "repos",
    "Label": false,
    "isTest": true,
    "Body": "\"\"\"\n        Is the correct error raised when we try to\n        do get_data with no data?\n        \"\"\"\npl = self.ctx.Plot()\nself.assertIsNone(pl.get_data())\n"
}