{
    "functionName": "test_chain_with_bad_chain_fails_on_access2",
    "className": "TestChain",
    "fileName": "/samreay_&_ChainConsumer/tests_&_test_chain.py",
    "projectName": "repos",
    "Label": false,
    "isTest": true,
    "Body": "c = Chain(self.bad, self.p, self.n)\nwith pytest.raises(AssertionError):\n    c.get_data(self.p[0])\n"
}